---
- hosts: all
  vars_files:
    - "{{ playbook_dir }}/vars/main.yml"
  tasks:
    - name: Run Generic Requirements Install
      include: "{{ playbook_dir }}/tasks/install-requirements.yml"
      when: requirements == false
    - name: Run Setup Postgres
      include: "{{ playbook_dir }}/tasks/setup-postgresql.yml"
      when: database == "postgresql"
#    - name: Run Setup MariaDB # Not currently supported :(
#      when: ( database == "mysql" or database == "mariadb" )
#      include "{{ playbook_dir }}/tasks/setup-mariadb.yml"
    - name: Run Setup Apache2 
      include: "{{ playbook_dir }}/tasks/setup-apache2.yml"
      when: (provider == "apache2" or provider == "httpd" )
    - name: Run Setup NGINX
      when: provider == "nginx"
      include: "{{ playbook_dir }}/tasks/setup-nginx.yml"
    - name: Run Generic App Setup
      include: "{{ playbook_dir }}/tasks/setup-generic.yml"
