---
- hosts: all
  vars:
    restya_user: "restya"
    restya_pass: "hjVl2rGd22"  
    restya_db: "restyaboard"
    restya_github: "https://github.com/RestyaPlatform/board.git"
    restya_apps_github: "https://github.com/RestyaPlatform/board-apps.git"
    restya_install_dir: "/usr/share/nginx/html/restyaboard"
    download_dir: "/opt/restyaboard"
    download_apps_dir: "{{ download_dir }}/client/apps"      
    postgres_host: "localhost"
    postgres_port: "5432"
    postgres_user: "postgres"
    postgres_pass: [] 
    postgres_conf: "/etc/postgresql/9.5/main/pg_hba.conf"
    nginx_domain: "my.exampledomain.com"
    smtp_user: []
    smtp_pass: []
    smtp_host: []
    smtp_port: []
    timezone: "America/Los_Angeles"
  tasks:
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - unzip
        - nginx-full
        - jq
        - python-software-properties
        - libjpeg8
        - php
        - postfix
        - php7.0-fpm
        - php7.0-cli
        - libpq5
        - php7.0-pgsql
        - php7.0-mbstring
        - php7.0-ldap
        - gcc
        - imagemagick
        - php7.0-imap
        - php7.0-xml
        - wget
        - ca-certificates
        - php7.0-geoip
        - php7.0-dev
        - libgeoip-dev
        - geoip-bin
        - autotools-dev
        - automake
        - erlang
        - libyaml-dev
        - rebar
        - curl
        - debian-keyring 
        - debian-archive-keyring
        - libnl-3-200
        - libnl-3-dev
        - libnl-genl-3-200
        - libnl-genl-3-dev
        - python-pip
        - expat
      become: true
    - name: create db  
      postgresql_user:
        name: "{{ restya_user }}"
        password: "{{ restya_pass }}"
        login_host: "{{ postgres_host }}"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_pass }}"
        port: "{{ postgres_port }}"
        state: present
      postgresql_db:
        name: "{{ restya_db }}"
        state: present
        owner: "{{ restya_user}}"
    - name: Grab git projects 
      git:
        repo: "{{ restya_github }}"
        dest: "{{ download_dir }}"
      become: true
    - name: Grab restya git apps
      git:
        repo: "{{ restya_apps_github }}"
        dest: "{{ download_apps_dir }}"
      become: true
    - name: setup php timezone
      lineinfile:
        path: /etc/php/7.0/fpm/php.ini
        regexp: ";date.timezone"
        line: "date.timezone = {{ timezone }}"
        backup: yes
        create: yes 
      become: true
    - name: change auth params in php
      lineinfile:
        path: "{{ postgres_conf }}"
        regexp: "(peer|ident)"
        line: "trust"
        backup: yes
        create: yes
      become: true
    - name: enable geopip phpext
      lineinfile:
        path: /etc/php.ini
        regexp: "extension=geoip.so"
        line: "extension=geoip.so"
        backup: yes
        create: yes  
      file:
        path: /usr/share/GeoIP
        state: directory
      become: true
    - name: get geo data
      command: get_geoip_data
    - name: setup nginx 
      lineinfile:
        path: /etc/nginx/conf.d/restyaboard.conf
        regexp: "server_name.*$"
        line: "server_name  {{ nginx_domain }} ;"
        backup: yes
        create: yes
      lineinfile:
        path: /etc/nginx/conf.d/restyaboard.conf
        regexp: "root.*html"
        line: "root  {{ restya_install_dir }}" 
      copy:
        src: "{{ download_dir }}/"
        dest: "{{ restya_install_dir }}"
        directory_mode: yes
      become: true
    - name: Setup Postfix
      shell: echo "postfix postfix/mailname string  {{ nginx_domain }}" | debconf-set-selections && echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
      become: true
    - name: Setup restya dir Perms
      file:
        path: "{{ item }}" 
        mode: 0775
        state: directory
      with_items:
        - "{{ restya_install_dir }}/media"
        - "{{ restya_install_dir }}/client/img"
        - "{{ restya_install_dir }}/tmp/cache"
      become: true
    - name: Setup restya shell file perms      
      file:
        path: "{{ restya_install_dir }}/server/php/*.sh"
        mode: 0755
        state: file
      become: true
    - name: create restya db
      postgresql_ext:
        db: "{{ restya_db }}"
        login_host: "{{ postgres_host }}"
        login_user: "{{ postgres_user }}"
        login_pass: "{{ postgres_pass }}"
        port: "{{ postgres_port }}"
        name: plpgsql
    - name: Import Postgres db
      command: psql -d  {{ restya_db }} -f  {{ restya_db }}/sql/restyaboard_with_empty_data.sql" -U  {{ postgres_user }}"
    - name: Setup PHP 
      lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.reg }}" 
        line: "{{ item.line }}"
        backup: yes
        create: yes
      with_items:
        - { path: "{{ restya_install_dir }}/server/php/config.inc.php", reg: "^.*'R_DB_NAME'.*$", line: "define('R_DB_NAME', '{{ restya_db }}');" }
        - { path: "{{ restya_install_dir }}/server/php/config.inc.php", reg: "^.*'R_DB_USER'.*$", line: "define('R_DB_USER', '{{ postgres_user }}');" }
        - { path: "{{ restya_install_dir }}/server/php/config.inc.php", reg: "^.*'R_DB_PASSWORD'.*$", line: "define('R_DB_PASSWORD', '{{ postgres_pass }}');" }
        - { path: "{{ restya_install_dir }}/server/php/config.inc.php", reg: "^.*'R_DB_HOST'.*$", line: "define('R_DB_HOST', '{{ postgres_host }}');" }
        - { path: "{{ restya_install_dir }}/server/php/config.inc.php", reg: "^.*'R_DB_PORT'.*$", line: "define('R_DB_PORT', '{{ postgres_port }}');" }
      become: yes
    - name: setup email notifications in cron
      cron:
        backup: yes
        minute:  "{{ item.minute }}" 
        job:  "{{ item.job }}"
      with_items:    
        { job: "{{ restya_install_dir }}/server/php/shell/instant_email_notification.sh", minute: "*/5" }
        { minute: "*/55", job: "{{ restya_install_dir }}/server/php/shell/periodic_email_notification.sh" }
        { minute: "*/30", job: "{{ restya_install_dir }}/server/php/shell/imap.sh" }
        { minute: "*/5", job: "{{ restya_install_dir }}/server/php/shell/webhook.sh" }
        { minute: "*/5", job: "{{ restya_install_dir }}/server/php/shell/card_due_notification.sh" }
    - name: setup php to use smtp
      lineinfile:
        path: /etc/php.ini
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }} "
      with_items:
        - { regexp: "1021 i auth_username = {{ smtp_user }}", line: "1021 i auth_username = {{ smtp_user }}" }
        - {    regexp: "1022 i auth_password = {{ smtp_pass }}", line: "1022 i auth_password = {{ smtp_pass }}" }
        - { regexp: "SMTP = .*$", line: "SMTP = {{ smtp_host }}" }
        - { regexp: "smtp_port = .*$", line: "smtp_port = {{ smtp_port }}" }
      become: true
    - name: Restart services
      service:
        name: "{{ item }} "
        state: restarted
      with_items:
        - "postgresql"
        - "cron"
        - "nginx"
        - "php7.0-fpm"
        - "postfix"
      become: true
