---
- hosts: all
  vars:
    restya_user: "restya"
    restya_pass: "hjVl2rGd22"  
    restya_db: "restyaboard"
    restya_github: "https://github.com/RestyaPlatform/board.git"
    restya_apps_github: "https://github.com/RestyaPlatform/board-apps.git"
    restya_install_dir: "/usr/share/nginx/html/restyaboard"
    download_dir: "/opt/restyaboard"
    download_apps_dir: "{{ download_dir }}/client/apps"      
    postgres_host: "localhost"
    postgres_port: [] # 5432
    postgres_user: "postgres"
    postgres_pass: [] 
    postgres_conf: "/etc/postgresql/9.5/main/pg_hba.conf" # This varies host to host and postgres version to version...
    nginx_domain: "my.exampledomain.com"
    smtp_user: []
    smtp_pass: []
    smtp_host: []
    smtp_port: []
    timezone: "America/Los_Angeles"
  tasks:    
    - name: Install standard packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - unzip
        - nginx-full
        - jq
        - python-software-properties
        - libjpeg8
        - php
        - postfix
        - php7.0-fpm
        - php7.0-cli
        - libpq5
        - php7.0-pgsql
        - php7.0-mbstring
        - php7.0-ldap
        - gcc
        - imagemagick
        - php7.0-imap
        - php7.0-xml
        - wget
        - ca-certificates
        - php-geoip
        - php7.0-dev
        - libgeoip-dev
        - geoip-bin
        - autotools-dev
        - automake
        - erlang
        - libyaml-dev
        - rebar
        - curl
        - debian-keyring 
        - debian-archive-keyring
        - libnl-3-200
        - libnl-3-dev
        - libnl-genl-3-200
        - libnl-genl-3-dev
        - python-pip
        - expat
        - python-pip 
        - python-dev 
        - libssl-dev 
        - build-essential 
        - libtool 
        - autoconf
      become: true
    - name: ensure latest version of ansible pip psycopg2
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - ansible
        - pip
        - psycopg2
    - name: Grab git projects 
      git:
        repo: "{{ restya_github }}"
        dest: "{{ download_dir }}"
      become: true
    - name: Grab restya git apps
      git:
        repo: "{{ restya_apps_github }}"
        dest: "{{ download_apps_dir }}"
      become: true
    - name: setup php timezone
      lineinfile:
        path: /etc/php/7.0/fpm/php.ini
        regexp: ";date.timezone"
        line: "date.timezone = {{ timezone }}"
        backup: yes
        create: yes 
      become: true
    - name: update postgres db conf
      copy:
        src: "{{ playbook_dir }}/defaults/pg_hba.conf"
        dest: "{{ postgres_conf }}"
        backup: yes
      become: true
    - name: enable geopip phpext
      lineinfile:
        path: /etc/php.ini
        regexp: "extension=geoip.so"
        line: "extension=geoip.so"
        backup: yes
        create: yes  
    - name: Create geoip dir
      file:
        path: /usr/share/GeoIP
        state: directory
      become: true
    - name: setup nginx 
      lineinfile:
        path: /etc/nginx/conf.d/restyaboard.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: yes
        create: yes
      with_items:
        - { regexp: "root.*html", line: "root  {{ restya_install_dir }}" }
        - { regexp: "server_name.*$", line: "server_name  {{ nginx_domain }} ;" }
    - name: Create restya install dir
      file:
        mode: 0775
        state: directory
        path: "{{ download_dir }}"
      become: true
    - name: Move restya to install dir
      synchronize:
        mode: pull
        src: "{{ download_dir }}/"
        dest: "/{{ restya_install_dir }}/"
      become: true
    - name: Setup Postfix
      shell: echo "postfix postfix/mailname string  {{ nginx_domain }}" | debconf-set-selections && echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections
      become: true
    - name: Setup restya dir Perms
      file: 
        path: "{{ item }}" 
        owner: www-data
        group: www-data
        mode: 0775
        state: directory
      with_items:
        - "{{ restya_install_dir }}/media"
        - "{{ restya_install_dir }}/client/img"
        - "{{ restya_install_dir }}/tmp/cache"
      become: true
    - name: Setup restya shell file perms      
      file: 
        path: "{{ restya_install_dir }}/server/php/shell/{{ item }}"
        mode: 0755
        state: file  
      with_items:
        - card_due_notification.sh
        - imap.sh
        - instant_email_notification.sh
        - periodic_email_notification.sh
        - webhook.sh
      become: true
    - name: create restya db
      postgresql_db:
        name: "{{ restya_db }}"
      become: true
      become_user: postgres
    - name: add restya db extenstion
      postgresql_ext:
        db: "{{ restya_db }}"
        name: plpgsql
      become: true
      become_user: postgres
    - name: create the db user
      postgresql_user:
        name: "{{ restya_user }}"
        password: "{{ restya_pass }}"
        db: "{{ restya_db }}"
        priv: ALL
        state: present
      become: true
      become_user: postgres
    - name: Import Postgres db
      command: "psql -d  {{ restya_db }} -f  {{ download_dir }}/sql/restyaboard_with_empty_data.sql" 
      become: true
      become_user: postgres
    - name: Setup PHP 
      lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.reg }}" 
        line: "{{ item.line }}"
        backup: yes
        create: yes
      with_items:
        - { path: "{{ restya_install_dir }}/server/php/config.inc.php", reg: "^.*'R_DB_NAME'.*$", line: "define('R_DB_NAME', '{{ restya_db }}');" }
        - { path: "{{ restya_install_dir }}/server/php/config.inc.php", reg: "^.*'R_DB_USER'.*$", line: "define('R_DB_USER', '{{ postgres_user }}');" }
        - { path: "{{ restya_install_dir }}/server/php/config.inc.php", reg: "^.*'R_DB_PASSWORD'.*$", line: "define('R_DB_PASSWORD', '{{ postgres_pass }}');" }
        - { path: "{{ restya_install_dir }}/server/php/config.inc.php", reg: "^.*'R_DB_HOST'.*$", line: "define('R_DB_HOST', '{{ postgres_host }}');" }
        - { path: "{{ restya_install_dir }}/server/php/config.inc.php", reg: "^.*'R_DB_PORT'.*$", line: "define('R_DB_PORT', '{{ postgres_port }}');" }
      become: yes
    - name: setup email notifications in cron
      cron:
        backup: yes
        minute:  "{{ item.minute }}" 
        job:  "{{ item.job }}"
      with_items:    
        - { job: "{{ restya_install_dir }}/server/php/shell/instant_email_notification.sh", minute: "*/5" }
        - { minute: "*/55", job: "{{ restya_install_dir }}/server/php/shell/periodic_email_notification.sh" }
        - { minute: "*/30", job: "{{ restya_install_dir }}/server/php/shell/imap.sh" }
        - { minute: "*/5", job: "{{ restya_install_dir }}/server/php/shell/webhook.sh" }
        - { minute: "*/5", job: "{{ restya_install_dir }}/server/php/shell/card_due_notification.sh" }
    - name: setup php to use smtp
      lineinfile:
        path: /etc/php.ini
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }} "
      with_items:
        - { regexp: "1021 i auth_username =", line: "1021 i auth_username = {{ smtp_user }}" }
        - { regexp: "1022 i auth_password =", line: "1022 i auth_password = {{ smtp_pass }}" }
        - { regexp: "SMTP =", line: "SMTP = {{ smtp_host }}" }
        - { regexp: "smtp_port =", line: "smtp_port = {{ smtp_port }}" }
      become: true
    - name: Restart services
      command: "service {{ item }} restart" # due to a bug with ansible and systemd, using this
      become: true
      with_items:
        - "postgresql"
        - "cron"
        - "nginx"
        - "php7.0-fpm"
        - "postfix"

