---
- hosts: local
  vars:
    restya_user: restya
    restya_pass: hjVl2!rGd22    
    restya_db: restyaboard
    restya_github: https://github.com/RestyaPlatform/board.git
    restya_apps_github: https://github.com/RestyaPlatform/board-apps.git
    install_dir: /opt/restyaboard
    install_apps_dir: {{ install_dir }}/client/apps            
    postgres_host: localhost
    postgres_port: 5432
    postgres_user: postgres
    postgres_pass:     
  name: install packages
    become: true
    package:
      name: "{{ item }}"
      state: present
  with_items:
    - postgresql
    - unzip
    - nginx-full
    - jq
    - python-software-properties
    - libjpeg8
    - php
    - php7.0-fpm
    - php7.0-cli
    - libpq5
    - php7.0-pgsql
    - php7.0-mbstring
    - php7.0-ldap
    - gcc
    - imagemagick
    - php7.0-imap
    - php7.0-xml
    - wget
    - ca-certificates
    - php7.0-geoip
    - php7.0-dev
    - libgeoip-dev
    - geoip
    - autotools-dev
    - automake
    - erlang
    - libyaml-dev
    - rebar
    - curl
    - debian-keyring 
    - debian-archive-keyring
    - libnl-3-200
    - libnl-3-dev
    - libnl-genl-3-200
    - libnl-genl-3-dev
  postgresql_user:
    name: {{ restya_user }}
    password: {{ restya_pass }}
    login_host: {{ postgres_host }}
    login_user: {{ postgres_user }}
    login_password: {{ postgres_pass }}
    port: {{ postgres_port }}
    state: present
  postgresql_db:
    name: {{ restya_db }}
    state: present
    owner: {{ restya_user}}
  git:
    repo: {{ restya_github }}
    dest: {{ install_dir }}
  git:
    repo: {{ restya_apps_github }}
    dest: {{ install_dir_apps }}
