---
- hosts: all  
  tasks:    
    - name: Include Vars
      include: "{{ playbook_dir }}/vars/main.yml"    
    - name: Install NGINX Packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx_full
    - name: setup nginx 
      lineinfile:
        path: /etc/nginx/conf.d/restyaboard.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        create: yes
      with_items:
        - { regexp: "root.*html", line: "root  {{ restya_install_dir }};" }  
    - name: Create NGINX SSL Directory
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: 0755
      become: true
    - name: Enable Let's Encrypt
      letsencrypt:
        account_key: "/etc/pki/cert/private/account.key"
        csr: "/etc/pki/cert/csr/{{ domain }}.csr"
        dest: "/etc/nginx/ssl/{{ domain }}.crt"
      when: letsencrypt_challenge_name != "sample_com_challenge"
      become: true
      register: "{{ letsencrypt_challenge_name }}"
    - name: Prepare SSL Request File
      when: letsencrypt_challenge_name == "sample_com_challenge"
      lineinfile:
        path: "{{ playbook_dir}}/defaults/ssl-request.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "C =" , line: "C = {{ cert_country }}" }
        - { regexp: "ST =", line: "ST = {{ cert_state }}" }
        - { regexp: "L =", line: "L = {{ cert_city }}" }
        - { regexp: "O =", line: "O = {{ company }}" }
        - { regexp: "emailAddress", line: " emailAddress = {{ admin_email }}" }
      become: true        
    - name: Create Self Signed Certificates
      command: "openssl req  -config {{ playbook_dir}}/defaults/ssl-request.conf -sha512 -x509 -nodes -days 365 -newkey rsa:4096 -keyout /etc/nginx/ssl/{{ domain }}.key -out /etc/nginx/ssl/{{ domain }}.crt"
      become: true
      when: letsencrypt_challenge_name == "sample_com_challenge"
    - name: Copy Nginx Config Over
      copy:
        src: "{{ playbook_dir }}/defaults/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        force: yes
        backup: yes    
    - name: Setup Nginx Conf File to Use cert and domain
      lineinfile:
        path: "/etc/nginx/nginx.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: ".*server_name .*$" , line: "server_name   {{ domain }} ;" }
        - { regexp: ".*ssl_certificate .*$" , line: "ssl_certificate   /etc/nginx/ssl/{{ domain }}.crt ;" }
        - { regexp: ".*ssl_certificate_key .*$" , line: "ssl_certificate_key   /etc/nginx/ssl/{{ domain }}.key;" }
        - { regexp: ".*listen .*$" , line: "listen    {{ web_port }} ssl;" }
      become: true
    - name: Ensure certs are in unix format
      command: "{{ item }}"
      become: true
      with_items:
        - "dos2unix /etc/nginx/ssl/{{ domain }}.crt"
        - "dos2unix /etc/nginx/ssl/{{ domain }}.key"
    - name: ensure permissions for nginx
      file:
        path: "{{ item }}"
        mode: 0500
        owner: www-data
        group: www-data
        state: file
      with_items:
        - /etc/nginx/ssl/{{ domain }}.crt
        - /etc/nginx/ssl/{{ domain }}.key
        - /etc/nginx/nginx.conf
      become: true
    - name: Restart services
      command: "service {{ item }} restart" # due to a bug with ansible and systemd, using this
      become: true
      with_items:
        - "nginx"


